##########################################################
#                       Log Levels                       #
##########################################################
logging.level.root=INFO
logging.level.com.garganttua=TRACE
logging.level.com.nextgentrace=TRACE

##########################################################
#              Spring Web Server Properties              #
##########################################################
server.port=8080
spring.profiles.default=DEV
spring.application.name=Garganttua API Example

##########################################################
#               Garganttua API Properties                #
##########################################################

com.garganttua.api.spring.scanPackages=com.garganttua
spring.data.mongodb.uri=mongodb://example-admin:example-admin@localhost:27017/garganttua-api-example

com.garganttua.api.interface.spring.rest.openapi.title=Example API
com.garganttua.api.interface.spring.rest.openapi.description=This is the restful API to access backend functions